name: Sync Github To Gitee
on: [push]
jobs:
    sync-blog:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Gitee
                uses: wearerequired/git-mirror-action@master
                env:
                    SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
                with:
                    source-repo: "https://github.com/captain9911/blog.git"
                    destination-repo: "https://gitee.com/captain9911/captain9911.git"
